version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: myapp-postgres
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword123!
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - poze_scheme_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d mydatabase"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  poze_scheme_data: